spring:
  # datasource configuration
  datasource:
    druid:
      url: jdbc:mysql://gz-cdb-drh06wqx.sql.tencentcdb.com:57613/easy_toastmasters?serverTimeZone=UTC
      username: lingbomanbu
      password: Lyl14786632348
      initial-size: 5
      max-active: 200
      max-wait: 2000
      test-on-borrow: false
      test-on-return: false
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  # thymeleaf configuration
  thymeleaf:
    cache: true
    check-template: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
# mybatis-plus configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true