spring:
  # datasource configuration
  datasource:
    druid:
      url: jdbc:mysql://gz-cdb-drh06wqx.sql.tencentcdb.com:57613/easy_toastmasters?serverTimeZone=UTC
      username: lingbomanbu
      password: Lyl14786632348
      initial-size: 5
      max-active: 200
      max-wait: 2000
      test-on-borrow: false
      test-on-return: false
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  # thymeleaf configuration
  thymeleaf:
    cache: true
    check-template: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  # internationalized configuration
  messages:
    basename: i18n.messages # basename也可以使用全限定类名
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/templates/
# mybatis-plus configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    use-generated-keys: true
# http client configuration
http:
  client:
    max-total: 500 # 连接池最大连接数
    default-max-per-route: 100 # 每个路由最大连接数
    max-idle-time: 5s # 连接最大空闲时间
    connection-request-timeout: 3s # 从连接池获取连接超时时间
    connection-timeout: 5s # 与服务端建立连接超时时间
    socket-timeout: 10s # 客户端从服务器读取数据超时时间